<a href="https://colab.research.google.com/github/amalasoy/Assignment/blob/main/case_study2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

####1.Basic array

In [1]:
import pandas as pd
data = pd.read_csv('auto-mpg.csv')
data

mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8         307.0        130    3504          12.0   
1    15.0          8         350.0        165    3693          11.5   
2    18.0          8         318.0        150    3436          11.0   
3    16.0          8         304.0        150    3433          12.0   
4    17.0          8         302.0        140    3449          10.5   
..    ...        ...           ...        ...     ...           ...   
393  27.0          4         140.0         86    2790          15.6   
394  44.0          4          97.0         52    2130          24.6   
395  32.0          4         135.0         84    2295          11.6   
396  28.0          4         120.0         79    2625          18.6   
397  31.0          4         119.0         82    2720          19.4   

     model year  origin                   car name  
0            70       1  chevrolet chevelle malibu  
1            70       1          buick skylark 320  
2            70       1         plymouth satellite  
3            70       1              amc rebel sst  
4            70       1                ford torino  
..          ...     ...                        ...  
393          82       1            ford mustang gl  
394          82       2                  vw pickup  
395          82       1              dodge rampage  
396          82       1                ford ranger  
397          82       1                 chevy s-10  

[398 rows x 9 columns]

In [2]:
data_mpg = data['mpg']
data_mpg

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ... 
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [3]:
data_mpg.values

array([18. , 15. , 18. , 16. , 17. , 15. , 14. , 14. , 14. , 15. , 15. ,
       14. , 15. , 14. , 24. , 22. , 18. , 21. , 27. , 26. , 25. , 24. ,
       25. , 26. , 21. , 10. , 10. , 11. ,  9. , 27. , 28. , 25. , 25. ,
       19. , 16. , 17. , 19. , 18. , 14. , 14. , 14. , 14. , 12. , 13. ,
       13. , 18. , 22. , 19. , 18. , 23. , 28. , 30. , 30. , 31. , 35. ,
       27. , 26. , 24. , 25. , 23. , 20. , 21. , 13. , 14. , 15. , 14. ,
       17. , 11. , 13. , 12. , 13. , 19. , 15. , 13. , 13. , 14. , 18. ,
       22. , 21. , 26. , 22. , 28. , 23. , 28. , 27. , 13. , 14. , 13. ,
       14. , 15. , 12. , 13. , 13. , 14. , 13. , 12. , 13. , 18. , 16. ,
       18. , 18. , 23. , 26. , 11. , 12. , 13. , 12. , 18. , 20. , 21. ,
       22. , 18. , 19. , 21. , 26. , 15. , 16. , 29. , 24. , 20. , 19. ,
       15. , 24. , 20. , 11. , 20. , 21. , 19. , 15. , 31. , 26. , 32. ,
       25. , 16. , 16. , 18. , 16. , 13. , 14. , 14. , 14. , 29. , 26. ,
       26. , 31. , 32. , 28. , 24. , 26. , 24. , 26

In [5]:
import numpy as np

In [8]:
mean = np.mean(data_mpg)
median = np.median(data_mpg)
print(mean,median)

23.514572864321607 23.0


In [13]:
from scipy import stats
mode =stats.mode(data_mpg)
mode

ModeResult(mode=np.float64(13.0), count=np.int64(20))

In [17]:
data_mpg_1 = [data_mpg>25]
data_mpg_1

[0      False
 1      False
 2      False
 3      False
 4      False
        ...  
 393     True
 394     True
 395     True
 396     True
 397     True
 Name: mpg, Length: 398, dtype: bool]

####2.Filtering

In [18]:
data_cars = data['car name']
data_cars

0      chevrolet chevelle malibu
1              buick skylark 320
2             plymouth satellite
3                  amc rebel sst
4                    ford torino
                 ...            
393              ford mustang gl
394                    vw pickup
395                dodge rampage
396                  ford ranger
397                   chevy s-10
Name: car name, Length: 398, dtype: object

In [19]:
data_cars.values

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino',
       'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
       'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
       "plymouth 'cuda 340", 'chevrolet monte carlo',
       'buick estate wagon (sw)', 'toyota corona mark ii',
       'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
       'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
       'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
       'dodge d200', 'hi 1200d', 'datsun pl510', 'chevrolet vega 2300',
       'toyota corona', 'ford pinto', 'amc gremlin',
       'plymouth satellite custom', 'chevrolet chevelle malibu',
       'ford torino 500', 'amc matador', 'chevrolet impala',
       'pontiac catalina brougham', 'ford galaxie 500',
       'plymouth fury iii', 'dodge monaco (sw)',
       'ford country squire (sw)', 'pontiac safari (sw)',
 

In [20]:
data_cylinder = data['cylinders']
data_cylinder

0      8
1      8
2      8
3      8
4      8
      ..
393    4
394    4
395    4
396    4
397    4
Name: cylinders, Length: 398, dtype: int64

In [21]:
data_cylinder.values

array([8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 4, 6, 6, 6, 4, 4, 4, 4,
       4, 4, 6, 8, 8, 8, 8, 4, 4, 4, 4, 6, 6, 6, 6, 6, 8, 8, 8, 8, 8, 8,
       8, 6, 4, 6, 6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8,
       8, 8, 8, 8, 8, 3, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8,
       8, 8, 8, 8, 8, 8, 8, 8, 8, 6, 6, 6, 6, 6, 4, 8, 8, 8, 8, 6, 4, 4,
       4, 3, 4, 6, 4, 8, 8, 4, 4, 4, 4, 8, 4, 6, 8, 6, 6, 6, 6, 4, 4, 4,
       4, 6, 6, 6, 8, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6,
       6, 6, 8, 8, 8, 8, 6, 6, 6, 6, 6, 8, 8, 4, 4, 6, 4, 4, 4, 4, 6, 4,
       6, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 8, 8, 8, 8, 6, 6, 6, 6, 4, 4, 4,
       4, 6, 6, 6, 6, 4, 4, 4, 4, 4, 8, 4, 6, 6, 8, 8, 8, 8, 4, 4, 4, 4,
       4, 8, 8, 8, 8, 6, 6, 6, 6, 8, 8, 8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 6,
       4, 3, 4, 4, 4, 4, 4, 8, 8, 8, 6, 6, 6, 4, 6, 6, 6, 6, 6, 6, 8, 6,
       8, 8, 4, 4, 4, 4, 4, 4, 4, 4, 5, 6, 4, 6, 4, 4, 6, 6, 4, 6, 6, 8,
       8, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 5, 8, 4, 8,

In [23]:
new_cars = np.array(data_cars)
new_cylinder = np.array(data_cylinder)
new_list = new_cars, new_cylinder>6
new_list

(array(['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino',
        'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
        'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
        "plymouth 'cuda 340", 'chevrolet monte carlo',
        'buick estate wagon (sw)', 'toyota corona mark ii',
        'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
        'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
        'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
        'dodge d200', 'hi 1200d', 'datsun pl510', 'chevrolet vega 2300',
        'toyota corona', 'ford pinto', 'amc gremlin',
        'plymouth satellite custom', 'chevrolet chevelle malibu',
        'ford torino 500', 'amc matador', 'chevrolet impala',
        'pontiac catalina brougham', 'ford galaxie 500',
        'plymouth fury iii', 'dodge monaco (sw)',
        'ford country squire (sw)', 'pontiac

In [52]:
new_list = {
    'car':['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino',
        'ford galaxie 500', 'chevrolet impala', 'plymouth fury iii',
        'pontiac catalina', 'amc ambassador dpl', 'dodge challenger se',
        "plymouth 'cuda 340", 'chevrolet monte carlo',
        'buick estate wagon (sw)', 'toyota corona mark ii',
        'plymouth duster', 'amc hornet', 'ford maverick', 'datsun pl510',
        'volkswagen 1131 deluxe sedan', 'peugeot 504', 'audi 100 ls',
        'saab 99e', 'bmw 2002', 'amc gremlin', 'ford f250', 'chevy c20',
        'dodge d200', 'hi 1200d', 'datsun pl510', 'chevrolet vega 2300',
        'toyota corona', 'ford pinto', 'amc gremlin',
        'plymouth satellite custom', 'chevrolet chevelle malibu',
        'ford torino 500', 'amc matador', 'chevrolet impala',
        'pontiac catalina brougham', 'ford galaxie 500',
        'plymouth fury iii', 'dodge monaco (sw)',
        'ford country squire (sw)', 'pontiac safari (sw)',
        'amc hornet sportabout (sw)', 'chevrolet vega (sw)',
        'pontiac firebird', 'ford mustang', 'mercury capri 2000',
        'opel 1900', 'peugeot 304', 'fiat 124b', 'toyota corolla 1200',
        'datsun 1200', 'volkswagen model 111', 'plymouth cricket',
        'toyota corona hardtop', 'dodge colt hardtop', 'volkswagen type 3',
        'chevrolet vega', 'ford pinto runabout', 'chevrolet impala',
        'pontiac catalina', 'plymouth fury iii', 'ford galaxie 500',
        'amc ambassador sst', 'mercury marquis', 'buick lesabre custom',
        'oldsmobile delta 88 royale', 'chrysler newport royal',
        'mazda rx2 coupe', 'amc matador (sw)',
        'chevrolet chevelle concours (sw)', 'ford gran torino (sw)',
        'plymouth satellite custom (sw)', 'volvo 145e (sw)',
        'volkswagen 411 (sw)', 'peugeot 504 (sw)', 'renault 12 (sw)',
        'ford pinto (sw)', 'datsun 510 (sw)',
        'toyouta corona mark ii (sw)', 'dodge colt (sw)',
        'toyota corolla 1600 (sw)', 'buick century 350', 'amc matador',
        'chevrolet malibu', 'ford gran torino', 'dodge coronet custom',
        'mercury marquis brougham', 'chevrolet caprice classic',
        'ford ltd', 'plymouth fury gran sedan',
        'chrysler new yorker brougham', 'buick electra 225 custom',
        'amc ambassador brougham', 'plymouth valiant',
        'chevrolet nova custom', 'amc hornet', 'ford maverick',
        'plymouth duster', 'volkswagen super beetle', 'chevrolet impala',
        'ford country', 'plymouth custom suburb',
        'oldsmobile vista cruiser', 'amc gremlin', 'toyota carina',
        'chevrolet vega', 'datsun 610', 'maxda rx3', 'ford pinto',
        'mercury capri v6', 'fiat 124 sport coupe',
        'chevrolet monte carlo s', 'pontiac grand prix', 'fiat 128',
        'opel manta', 'audi 100ls', 'volvo 144ea', 'dodge dart custom',
        'saab 99le', 'toyota mark ii', 'oldsmobile omega',
        'plymouth duster', 'ford maverick', 'amc hornet', 'chevrolet nova',
        'datsun b210', 'ford pinto', 'toyota corolla 1200',
        'chevrolet vega', 'chevrolet chevelle malibu classic',
        'amc matador', 'plymouth satellite sebring', 'ford gran torino',
        'buick century luxus (sw)', 'dodge coronet custom (sw)',
        'ford gran torino (sw)', 'amc matador (sw)', 'audi fox',
        'volkswagen dasher', 'opel manta', 'toyota corona', 'datsun 710',
        'dodge colt', 'fiat 128', 'fiat 124 tc', 'honda civic', 'subaru',
        'fiat x1.9', 'plymouth valiant custom', 'chevrolet nova',
        'mercury monarch', 'ford maverick', 'pontiac catalina',
        'chevrolet bel air', 'plymouth grand fury', 'ford ltd',
        'buick century', 'chevroelt chevelle malibu', 'amc matador',
        'plymouth fury', 'buick skyhawk', 'chevrolet monza 2+2',
        'ford mustang ii', 'toyota corolla', 'ford pinto', 'amc gremlin',
        'pontiac astro', 'toyota corona', 'volkswagen dasher',
        'datsun 710', 'ford pinto', 'volkswagen rabbit', 'amc pacer',
        'audi 100ls', 'peugeot 504', 'volvo 244dl', 'saab 99le',
        'honda civic cvcc', 'fiat 131', 'opel 1900', 'capri ii',
        'dodge colt', 'renault 12tl', 'chevrolet chevelle malibu classic',
        'dodge coronet brougham', 'amc matador', 'ford gran torino',
        'plymouth valiant', 'chevrolet nova', 'ford maverick',
        'amc hornet', 'chevrolet chevette', 'chevrolet woody', 'vw rabbit',
        'honda civic', 'dodge aspen se', 'ford granada ghia',
        'pontiac ventura sj', 'amc pacer d/l', 'volkswagen rabbit',
        'datsun b-210', 'toyota corolla', 'ford pinto', 'volvo 245',
        'plymouth volare premier v8', 'peugeot 504', 'toyota mark ii',
        'mercedes-benz 280s', 'cadillac seville', 'chevy c10', 'ford f108',
        'dodge d100', 'honda accord cvcc', 'buick opel isuzu deluxe',
        'renault 5 gtl', 'plymouth arrow gs', 'datsun f-10 hatchback',
        'chevrolet caprice classic', 'oldsmobile cutlass supreme',
        'dodge monaco brougham', 'mercury cougar brougham',
        'chevrolet concours', 'buick skylark', 'plymouth volare custom',
        'ford granada', 'pontiac grand prix lj',
        'chevrolet monte carlo landau', 'chrysler cordoba',
        'ford thunderbird', 'volkswagen rabbit custom',
        'pontiac sunbird coupe', 'toyota corolla liftback',
        'ford mustang ii 2+2', 'chevrolet chevette', 'dodge colt m/m',
        'subaru dl', 'volkswagen dasher', 'datsun 810', 'bmw 320i',
        'mazda rx-4', 'volkswagen rabbit custom diesel', 'ford fiesta',
        'mazda glc deluxe', 'datsun b210 gx', 'honda civic cvcc',
        'oldsmobile cutlass salon brougham', 'dodge diplomat',
        'mercury monarch ghia', 'pontiac phoenix lj', 'chevrolet malibu',
        'ford fairmont (auto)', 'ford fairmont (man)', 'plymouth volare',
        'amc concord', 'buick century special', 'mercury zephyr',
        'dodge aspen', 'amc concord d/l', 'chevrolet monte carlo landau',
        'buick regal sport coupe (turbo)', 'ford futura',
        'dodge magnum xe', 'chevrolet chevette', 'toyota corona',
        'datsun 510', 'dodge omni', 'toyota celica gt liftback',
        'plymouth sapporo', 'oldsmobile starfire sx', 'datsun 200-sx',
        'audi 5000', 'volvo 264gl', 'saab 99gle', 'peugeot 604sl',
        'volkswagen scirocco', 'honda accord lx', 'pontiac lemans v6',
        'mercury zephyr 6', 'ford fairmont 4', 'amc concord dl 6',
        'dodge aspen 6', 'chevrolet caprice classic', 'ford ltd landau',
        'mercury grand marquis', 'dodge st. regis',
        'buick estate wagon (sw)', 'ford country squire (sw)',
        'chevrolet malibu classic (sw)',
        'chrysler lebaron town @ country (sw)', 'vw rabbit custom',
        'maxda glc deluxe', 'dodge colt hatchback custom', 'amc spirit dl',
        'mercedes benz 300d', 'cadillac eldorado', 'peugeot 504',
        'oldsmobile cutlass salon brougham', 'plymouth horizon',
        'plymouth horizon tc3', 'datsun 210', 'fiat strada custom',
        'buick skylark limited', 'chevrolet citation',
        'oldsmobile omega brougham', 'pontiac phoenix', 'vw rabbit',
        'toyota corolla tercel', 'chevrolet chevette', 'datsun 310',
        'chevrolet citation', 'ford fairmont', 'amc concord',
        'dodge aspen', 'audi 4000', 'toyota corona liftback', 'mazda 626',
        'datsun 510 hatchback', 'toyota corolla', 'mazda glc',
        'dodge colt', 'datsun 210', 'vw rabbit c (diesel)',
        'vw dasher (diesel)', 'audi 5000s (diesel)', 'mercedes-benz 240d',
        'honda civic 1500 gl', 'renault lecar deluxe', 'subaru dl',
        'vokswagen rabbit', 'datsun 280-zx', 'mazda rx-7 gs',
        'triumph tr7 coupe', 'ford mustang cobra', 'honda accord',
        'plymouth reliant', 'buick skylark', 'dodge aries wagon (sw)',
        'chevrolet citation', 'plymouth reliant', 'toyota starlet',
        'plymouth champ', 'honda civic 1300', 'subaru', 'datsun 210 mpg',
        'toyota tercel', 'mazda glc 4', 'plymouth horizon 4',
        'ford escort 4w', 'ford escort 2h', 'volkswagen jetta',
        'renault 18i', 'honda prelude', 'toyota corolla', 'datsun 200sx',
        'mazda 626', 'peugeot 505s turbo diesel', 'volvo diesel',
        'toyota cressida', 'datsun 810 maxima', 'buick century',
        'oldsmobile cutlass ls', 'ford granada gl',
        'chrysler lebaron salon', 'chevrolet cavalier',
        'chevrolet cavalier wagon', 'chevrolet cavalier 2-door',
        'pontiac j2000 se hatchback', 'dodge aries se', 'pontiac phoenix',
        'ford fairmont futura', 'amc concord dl', 'volkswagen rabbit l',
        'mazda glc custom l', 'mazda glc custom', 'plymouth horizon miser',
        'mercury lynx l', 'nissan stanza xe', 'honda accord',
        'toyota corolla', 'honda civic', 'honda civic (auto)',
        'datsun 310 gx', 'buick century limited',
        'oldsmobile cutlass ciera (diesel)', 'chrysler lebaron medallion',
        'ford granada l', 'toyota celica gt', 'dodge charger 2.2',
        'chevrolet camaro', 'ford mustang gl', 'vw pickup',
        'dodge rampage', 'ford ranger', 'chevy s-10'],
    'mpg': [True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False,  True,  True,  True,  True,  True,  True,  True,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True, False, False, False, False, False,
        False, False, False, False,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True, False, False,
        False, False, False, False,  True,  True,  True,  True, False,
        False, False, False, False, False, False, False,  True,  True,
        False, False, False, False,  True, False, False,  True, False,
        False, False, False, False, False, False, False, False, False,
        False,  True,  True,  True,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False,  True,  True,  True,  True, False, False,
        False, False, False,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False,  True,  True,
         True,  True, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False,  True, False, False, False,  True,  True,  True,  True,
        False, False, False, False, False,  True,  True,  True,  True,
        False, False, False, False,  True,  True,  True,  True, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True,  True,
        False, False, False, False, False, False, False, False, False,
        False,  True, False,  True,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False,  True,  True,  True,
         True,  True,  True,  True,  True, False, False, False, False,
        False,  True, False,  True, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False,  True, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False,
        False, False]
}
return_list = pd.DataFrame(new_list)
return_list

car    mpg
0    chevrolet chevelle malibu   True
1            buick skylark 320   True
2           plymouth satellite   True
3                amc rebel sst   True
4                  ford torino   True
..                         ...    ...
393            ford mustang gl  False
394                  vw pickup  False
395              dodge rampage  False
396                ford ranger  False
397                 chevy s-10  False

[398 rows x 2 columns]

In [55]:
data_weight = data['weight']
min_weight = data_weight.min()
max_weight = data_weight.max()
normalized_weight = (data_weight - min_weight) / (max_weight - min_weight)
normalized_weight

0      3504
1      3693
2      3436
3      3433
4      3449
       ... 
393    2790
394    2130
395    2295
396    2625
397    2720
Name: weight, Length: 398, dtype: int64

In [56]:
data_weight.values

array([3504, 3693, 3436, 3433, 3449, 4341, 4354, 4312, 4425, 3850, 3563,
       3609, 3761, 3086, 2372, 2833, 2774, 2587, 2130, 1835, 2672, 2430,
       2375, 2234, 2648, 4615, 4376, 4382, 4732, 2130, 2264, 2228, 2046,
       2634, 3439, 3329, 3302, 3288, 4209, 4464, 4154, 4096, 4955, 4746,
       5140, 2962, 2408, 3282, 3139, 2220, 2123, 2074, 2065, 1773, 1613,
       1834, 1955, 2278, 2126, 2254, 2408, 2226, 4274, 4385, 4135, 4129,
       3672, 4633, 4502, 4456, 4422, 2330, 3892, 4098, 4294, 4077, 2933,
       2511, 2979, 2189, 2395, 2288, 2506, 2164, 2100, 4100, 3672, 3988,
       4042, 3777, 4952, 4464, 4363, 4237, 4735, 4951, 3821, 3121, 3278,
       2945, 3021, 2904, 1950, 4997, 4906, 4654, 4499, 2789, 2279, 2401,
       2379, 2124, 2310, 2472, 2265, 4082, 4278, 1867, 2158, 2582, 2868,
       3399, 2660, 2807, 3664, 3102, 2875, 2901, 3336, 1950, 2451, 1836,
       2542, 3781, 3632, 3613, 4141, 4699, 4457, 4638, 4257, 2219, 1963,
       2300, 1649, 2003, 2125, 2108, 2246, 2489, 23

####3.statistical Analysis

In [57]:
Q1 = np.percentile(data_weight,25)
Q2 = np.percentile(data_weight,50)
Q3= np.percentile(data_weight,75)
Q1,Q2,Q3

(np.float64(2223.75), np.float64(2803.5), np.float64(3608.0))

####4.Array manipulation

In [58]:
data_acceleration = data['acceleration']
data_acceleration

0      12.0
1      11.5
2      11.0
3      12.0
4      10.5
       ... 
393    15.6
394    24.6
395    11.6
396    18.6
397    19.4
Name: acceleration, Length: 398, dtype: float64

In [59]:
data_acceleration.values

array([12. , 11.5, 11. , 12. , 10.5, 10. ,  9. ,  8.5, 10. ,  8.5, 10. ,
        8. ,  9.5, 10. , 15. , 15.5, 15.5, 16. , 14.5, 20.5, 17.5, 14.5,
       17.5, 12.5, 15. , 14. , 15. , 13.5, 18.5, 14.5, 15.5, 14. , 19. ,
       13. , 15.5, 15.5, 15.5, 15.5, 12. , 11.5, 13.5, 13. , 11.5, 12. ,
       12. , 13.5, 19. , 15. , 14.5, 14. , 14. , 19.5, 14.5, 19. , 18. ,
       19. , 20.5, 15.5, 17. , 23.5, 19.5, 16.5, 12. , 12. , 13.5, 13. ,
       11.5, 11. , 13.5, 13.5, 12.5, 13.5, 12.5, 14. , 16. , 14. , 14.5,
       18. , 19.5, 18. , 16. , 17. , 14.5, 15. , 16.5, 13. , 11.5, 13. ,
       14.5, 12.5, 11.5, 12. , 13. , 14.5, 11. , 11. , 11. , 16.5, 18. ,
       16. , 16.5, 16. , 21. , 14. , 12.5, 13. , 12.5, 15. , 19. , 19.5,
       16.5, 13.5, 18.5, 14. , 15.5, 13. ,  9.5, 19.5, 15.5, 14. , 15.5,
       11. , 14. , 13.5, 11. , 16.5, 17. , 16. , 17. , 19. , 16.5, 21. ,
       17. , 17. , 18. , 16.5, 14. , 14.5, 13.5, 16. , 15.5, 16.5, 15.5,
       14.5, 16.5, 19. , 14.5, 15.5, 14. , 15. , 15

In [65]:
min_arr = np.min(data_weight)
max_arr = np.max(data_weight)
for i in data_weight():
    N = (i-min_arr)/(max_arr-min_arr)
    N_list.append
print(N_list)

TypeError: 'Series' object is not callable

####5.Broad casting

In [66]:
data_hp = data['horsepower']
data_hp

0      130
1      165
2      150
3      150
4      140
      ... 
393     86
394     52
395     84
396     79
397     82
Name: horsepower, Length: 398, dtype: object

In [67]:
data_hp.values

array(['130', '165', '150', '150', '140', '198', '220', '215', '225',
       '190', '170', '160', '150', '225', '95', '95', '97', '85', '88',
       '46', '87', '90', '95', '113', '90', '215', '200', '210', '193',
       '88', '90', '95', '?', '100', '105', '100', '88', '100', '165',
       '175', '153', '150', '180', '170', '175', '110', '72', '100', '88',
       '86', '90', '70', '76', '65', '69', '60', '70', '95', '80', '54',
       '90', '86', '165', '175', '150', '153', '150', '208', '155', '160',
       '190', '97', '150', '130', '140', '150', '112', '76', '87', '69',
       '86', '92', '97', '80', '88', '175', '150', '145', '137', '150',
       '198', '150', '158', '150', '215', '225', '175', '105', '100',
       '100', '88', '95', '46', '150', '167', '170', '180', '100', '88',
       '72', '94', '90', '85', '107', '90', '145', '230', '49', '75',
       '91', '112', '150', '110', '122', '180', '95', '?', '100', '100',
       '67', '80', '65', '75', '100', '110', '105', '140', '1

In [99]:
hp_replace = data_hp.replace('?', np.nan)
hp_num = pd.to_numeric(hp_replace, errors='coerce')
mean_hp = np.mean(hp_num)
data_hp = hp_num.fillna(mean_hp)
data_hp

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...  
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 398, dtype: float64

In [104]:
data_hp1=data_hp.values
data_hp1

array([134.        , 169.        , 154.        , 154.        ,
       144.        , 202.        , 224.        , 219.        ,
       229.        , 194.        , 174.        , 164.        ,
       154.        , 229.        ,  99.        ,  99.        ,
       101.        ,  89.        ,  92.        ,  50.        ,
        91.        ,  94.        ,  99.        , 117.        ,
        94.        , 219.        , 204.        , 214.        ,
       197.        ,  92.        ,  94.        ,  99.        ,
       108.46938776, 104.        , 109.        , 104.        ,
        92.        , 104.        , 169.        , 179.        ,
       157.        , 154.        , 184.        , 174.        ,
       179.        , 114.        ,  76.        , 104.        ,
        92.        ,  90.        ,  94.        ,  74.        ,
        80.        ,  69.        ,  73.        ,  64.        ,
        74.        ,  99.        ,  84.        ,  58.        ,
        94.        ,  90.        , 169.        , 179.  

In [113]:
data_hp = data_hp1 *0.1
data_hp
data_hp2 = data_hp * np.mean(data_hp1)
data_hp2

array([1453.48979592, 1833.13265306, 1670.42857143, 1670.42857143,
       1561.95918367, 2191.08163265, 2429.71428571, 2375.47959184,
       2483.94897959, 2104.30612245, 1887.36734694, 1778.89795918,
       1670.42857143, 2483.94897959, 1073.84693878, 1073.84693878,
       1095.54081633,  965.37755102,  997.91836735,  542.34693878,
        987.07142857, 1019.6122449 , 1073.84693878, 1269.09183673,
       1019.6122449 , 2375.47959184, 2212.7755102 , 2321.24489796,
       2136.84693878,  997.91836735, 1019.6122449 , 1073.84693878,
       1176.560808  , 1128.08163265, 1182.31632653, 1128.08163265,
        997.91836735, 1128.08163265, 1833.13265306, 1941.60204082,
       1702.96938776, 1670.42857143, 1995.83673469, 1887.36734694,
       1941.60204082, 1236.55102041,  824.36734694, 1128.08163265,
        997.91836735,  976.2244898 , 1019.6122449 ,  802.67346939,
        867.75510204,  748.43877551,  791.82653061,  694.20408163,
        802.67346939, 1073.84693878,  911.14285714,  629.12244

####6.Boolean

In [116]:
s_data = data[data['origin'] == 2]
displacement = s_data['displacement']

displacement

19      97.0
20     110.0
21     107.0
22     104.0
23     121.0
       ...  
354    100.0
359    141.0
360    145.0
375    105.0
394     97.0
Name: displacement, Length: 70, dtype: float64

In [118]:
data_mpg_mean = data[['cylinders','mpg']]
data_mpg_mean

cylinders   mpg
0            8  18.0
1            8  15.0
2            8  18.0
3            8  16.0
4            8  17.0
..         ...   ...
393          4  27.0
394          4  44.0
395          4  32.0
396          4  28.0
397          4  31.0

[398 rows x 2 columns]

In [119]:
data_mpg_mean.values

array([[ 8. , 18. ],
       [ 8. , 15. ],
       [ 8. , 18. ],
       [ 8. , 16. ],
       [ 8. , 17. ],
       [ 8. , 15. ],
       [ 8. , 14. ],
       [ 8. , 14. ],
       [ 8. , 14. ],
       [ 8. , 15. ],
       [ 8. , 15. ],
       [ 8. , 14. ],
       [ 8. , 15. ],
       [ 8. , 14. ],
       [ 4. , 24. ],
       [ 6. , 22. ],
       [ 6. , 18. ],
       [ 6. , 21. ],
       [ 4. , 27. ],
       [ 4. , 26. ],
       [ 4. , 25. ],
       [ 4. , 24. ],
       [ 4. , 25. ],
       [ 4. , 26. ],
       [ 6. , 21. ],
       [ 8. , 10. ],
       [ 8. , 10. ],
       [ 8. , 11. ],
       [ 8. ,  9. ],
       [ 4. , 27. ],
       [ 4. , 28. ],
       [ 4. , 25. ],
       [ 4. , 25. ],
       [ 6. , 19. ],
       [ 6. , 16. ],
       [ 6. , 17. ],
       [ 6. , 19. ],
       [ 6. , 18. ],
       [ 8. , 14. ],
       [ 8. , 14. ],
       [ 8. , 14. ],
       [ 8. , 14. ],
       [ 8. , 12. ],
       [ 8. , 13. ],
       [ 8. , 13. ],
       [ 6. , 18. ],
       [ 4. , 22. ],
       [ 6. ,

In [117]:
g_by = data.groupby('cylinders')
g_by.mean('mpg')

mpg  displacement       weight  acceleration  model year  \
cylinders                                                                   
3          20.550000     72.500000  2398.500000     13.250000   75.500000   
4          29.286765    109.796569  2308.127451     16.601471   77.073529   
5          27.366667    145.000000  3103.333333     18.633333   79.000000   
6          19.985714    218.142857  3198.226190     16.263095   75.928571   
8          14.963107    345.009709  4114.718447     12.955340   73.902913   

             origin  
cylinders            
3          3.000000  
4          1.985294  
5          2.000000  
6          1.190476  
8          1.000000